build: test

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -28,26 +28,53 @@ concurrency:
 jobs:
   # Build job
   build:
-    runs-on: ubuntu-latest
+    runs-on: macos-10.15
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-      - name: Setup Docker Container
+      - name: Install pnpm
+        run: npm install -g pnpm
+      - name: Detect package manager
+        id: detect-package-manager
         run: |
-          docker run -d --name build-container -v ${{ github.workspace }}:/workspace -w /workspace node:lts-alpine
-      - name: Install pnpm in Docker Container
-        run: docker exec build-container sh -c "npm install -g pnpm"
-      - name: Install dependencies in Docker Container
-        run: docker exec build-container sh -c "pnpm install"
-      - name: Build with Next.js in Docker Container
-        run: docker exec build-container sh -c "pnpm next build"
-      - name: Static HTML export with Next.js in Docker Container
-        run: docker exec build-container sh -c "pnpm next export"
+          if [ -f "${{ github.workspace }}/pnpm-lock.yaml" ]; then
+            echo "manager=pnpm" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=pnpm" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20"
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+      - name: Setup Pages
+        uses: actions/configure-pages@v4
+        with:
+          static_site_generator: next
+      - name: Restore cache
+        uses: actions/cache@v4
+        with:
+          path: |
+            .next/cache
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+          restore-keys: |
+            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
+      - name: Install dependencies
+        run: ${{ steps.detect-package-manager.outputs.runner }} ${{ steps.detect-package-manager.outputs.command }}
+      - name: Build with Next.js
+        run: ${{ steps.detect-package-manager.outputs.runner }} next build
+      - name: Static HTML export with Next.js
+        run: ${{ steps.detect-package-manager.outputs.runner }} next export
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
           path: ./dist
   
+
   # Deployment job
   deploy:
     environment:
